
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job for the frontend
  frontend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the same Node.js version you use locally

      # Step 3: Install dependencies for the frontend
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      # Step 4: Run frontend tests
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test

      # Step 5: Build the frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  # Job for the backend
  backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for the backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Same Node.js version for backend

      # Step 3: Install dependencies for the backend
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # Step 4: Set up SQLite for the backend (if needed)
      - name: Set up SQLite
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      # Step 5: Run backend tests
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      # Step 6: Build the backend
      - name: Build Backend
        working-directory: ./backend
        run: npm run build
