name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]  # Specify OS for compatibility
    
    steps:
      # Check out code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install Jest as a dev dependency
      - name: Install Jest and dependencies
        working-directory: ./new design
        run: |
          npm install
          npm install --save-dev jest  # Adds Jest as a dev dependency if not already installed

      # Run Frontend Tests
      - name: Run Frontend Tests
        working-directory: ./new design
        run: npm test

      - name: Build Frontend
        working-directory: ./new design
        run: npm run build

      # Backend Setup and Build
      - name: Install Backend Dependencies
        working-directory: ./new design/backend
        run: npm install

      - name: Set up SQLite
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Run Backend Tests
        working-directory: ./new design/backend
        run: npm test

      - name: Build Backend
        working-directory: ./new design/backend
        run: npm run build
