name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]  # Specify OS for compatibility
    
    steps:
      # Check out code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Frontend Tests and Build
      - name: Install Frontend Dependencies
        working-directory: ./Project/frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./Project/frontend
        env:
          NODE_ENV: test
        run: npm test

      - name: Build Frontend
        working-directory: ./Project/frontend
        run: npm run build

      # Backend Tests and Setup
      - name: Install Backend Dependencies
        working-directory: ./Project/backend
        run: npm install

      - name: Set up SQLite
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Run Backend Tests
        working-directory: ./Project/backend
        run: npm test

      - name: Build Backend
        working-directory: ./Project/backend
        run: npm run build
